import Link from 'next/link'
import { ArrowRight, BarChart3, CreditCard, ExternalLink, FileText, Link2, ShieldCheck, Ticket, Users } from 'lucide-react'
import { getCurrentUser } from '@/lib/auth'
import { prisma } from '@/lib/prisma'

export default async function AdminPage() {
  const user = await getCurrentUser()
  if (!user || !user.isStaff) return <main className="admin-guard"><ShieldCheck size={28} /><h1>لوحة الإدارة محمية</h1><p>تحتاج إلى حساب Staff مصرح للوصول إلى بيانات التشغيل. لا تعتمد هذه الصفحة على إخفاء زر فقط.</p><Link href="/dashboard" className="button button-dark"><ArrowRight size={14} /> العودة للوحة التحكم</Link></main>
  const [teachers, subscriptions, tickets, links, invoices, audits] = await Promise.all([
    prisma.user.count({ where: { workspace: { isNot: null } } }),
    prisma.subscription.count({ where: { status: 'ACTIVE' } }),
    prisma.supportTicket.count({ where: { status: { in: ['OPEN', 'IN_PROGRESS', 'WAITING_ON_CUSTOMER'] } } }),
    prisma.lmsLink.count(),
    prisma.invoice.count({ where: { status: 'PAID' } }),
    prisma.auditLog.findMany({ orderBy: { createdAt: 'desc' }, take: 8, select: { id: true, action: true, entity: true, createdAt: true, actor: { select: { email: true } }, workspace: { select: { name: true } } } }),
  ])
  return <main className="admin-page"><header className="admin-header section-container"><Link href="/dashboard" className="brand"><span className="brand-mark"><span /><span /><span /></span>مركزية</Link><div><span className="section-eyebrow"><span className="eyebrow-dot" />مساحة الموظفين</span><h1>لوحة تشغيل <em>SaaS</em></h1></div><span className="staff-badge"><ShieldCheck size={13} /> Staff</span></header><section className="admin-content section-container"><div className="admin-metrics"><article><Users size={17} /><span>المدرسون</span><strong>{teachers}</strong></article><article><CreditCard size={17} /><span>اشتراكات نشطة</span><strong>{subscriptions}</strong></article><article><Ticket size={17} /><span>تذاكر مفتوحة</span><strong>{tickets}</strong></article><article><Link2 size={17} /><span>روابط LMS محفوظة</span><strong>{links}</strong></article></div><div className="admin-grid"><article className="admin-panel"><div className="admin-panel-heading"><div><b>نظرة تشغيلية</b><span>بيانات SaaS فقط، دون قراءة لمحتوى LMS.</span></div><BarChart3 size={17} /></div><div className="admin-stat-row"><span>الفواتير المدفوعة</span><strong>{invoices}</strong></div><div className="admin-stat-row"><span>حالة العزل</span><strong className="safe-state">مفعّل</strong></div><div className="admin-stat-row"><span>مصدر Usage</span><strong>غير متاح دون API رسمي</strong></div></article><article className="admin-panel"><div className="admin-panel-heading"><div><b>روابط سريعة</b><span>إدارة السطح التجاري للحسابات.</span></div><ExternalLink size={17} /></div><div className="admin-links"><Link href="/admin/plans"><CreditCard size={14} /> الخطط</Link><Link href="/admin/teachers"><Users size={14} /> المدرسون</Link><Link href="/admin/subscriptions"><CreditCard size={14} /> الاشتراكات</Link><Link href="/admin/billing"><Ticket size={14} /> الفوترة</Link><Link href="/admin/lms-links"><Link2 size={14} /> روابط المنصات</Link><Link href="/support"><Ticket size={14} /> الدعم والتذاكر</Link></div></article></div><article className="admin-panel audit-panel"><div className="admin-panel-heading"><div><b>آخر أحداث التدقيق</b><span>كل حدث مرتبط بفاعل ومساحة عمل عند توفرهما.</span></div><FileText size={17} /></div><div className="audit-list">{audits.map((audit) => <div className="audit-row" key={audit.id}><span>{audit.action}</span><b>{audit.entity}</b><small>{audit.actor?.email || 'system'} · {audit.workspace?.name || '—'} · {audit.createdAt.toLocaleString('ar-EG')}</small></div>)}</div></article></section></main>
}
