import Link from 'next/link'
import { ArrowRight, BarChart3, Bell, CreditCard, ExternalLink, FileText, Link2, LifeBuoy, PlugZap, ScrollText, Settings, ShieldCheck, UserCog, Users } from 'lucide-react'
import { getCurrentUser, staffTwoFactorRequired } from '@/lib/auth'
import { prisma } from '@/lib/prisma'
import { canAccessStaffSection, staffRoleLabels } from '@/lib/staff-access'
import type { ReactNode } from 'react'

const sections = {
  teachers: { title: 'المدرسون', description: 'حسابات المستخدمين المرتبطة بمساحات عمل SaaS.', icon: Users },
  plans: { title: 'الخطط', description: 'كتالوج الخطط التجارية الذي يديره SaaS.', icon: CreditCard },
  subscriptions: { title: 'الاشتراكات', description: 'حالات الاشتراك ومواعيدها دون بيانات دفع حساسة.', icon: CreditCard },
  billing: { title: 'الفوترة', description: 'الفواتير المملوكة لـ SaaS وحالاتها التجارية.', icon: CreditCard },
  'lms-links': { title: 'روابط المنصات', description: 'مراجع الروابط المحفوظة، لا محتوى LMS.', icon: Link2 },
  integrations: { title: 'التكاملات', description: 'طلبات التكامل وحالة الروابط المرجعية.', icon: PlugZap },
  usage: { title: 'الاستخدام', description: 'مقاييس تشغيل SaaS الفعلية دون اختلاق بيانات تعليمية.', icon: BarChart3 },
  reports: { title: 'التقارير', description: 'ملخصات تشغيلية قابلة للمراجعة.', icon: FileText },
  support: { title: 'الدعم', description: 'تذاكر العملاء وحالات المتابعة.', icon: LifeBuoy },
  staff: { title: 'الموظفون', description: 'حسابات Staff المصرح لها بالتشغيل.', icon: UserCog },
  audit: { title: 'سجل التدقيق', description: 'الأحداث الحساسة المسجلة داخل SaaS.', icon: ScrollText },
  notifications: { title: 'الإشعارات', description: 'إشعارات الحساب المحفوظة وحالتها.', icon: Bell },
  coupons: { title: 'أكواد الخصم', description: 'حالة الأكواد التجارية المحلية دون بيانات دفع حساسة.', icon: CreditCard },
  webhooks: { title: 'أحداث الدفع', description: 'صحة استقبال ومعالجة Webhook دون عرض الحمولة.', icon: ShieldCheck },
  settings: { title: 'إعدادات النظام', description: 'حدود النظام وبيانات التشغيل الحالية.', icon: Settings },
} as const

type SectionKey = keyof typeof sections

function formatDate(value: Date | string | null | undefined) {
  return value ? new Date(value).toLocaleString('ar-EG') : '—'
}

function emptyState() { return <div className="invoice-empty">لا توجد سجلات في هذا القسم.</div> }
function row(key: string, values: ReactNode[]) { return <div className="invoice-row" key={key}>{values.map((value, index) => <span key={`${key}-${index}`}>{value}</span>)}</div> }

export default async function AdminSectionPage({ params, searchParams }: { params: Promise<{ section: string }>; searchParams: Promise<{ q?: string }> }) {
  const { section } = await params
  const { q: rawQuery } = await searchParams
  const query = rawQuery?.trim().slice(0, 120) || ''
  const config = sections[section as SectionKey]
  const user = await getCurrentUser()
  if (!user || !user.isStaff) return <main className="admin-guard"><ShieldCheck size={28} /><h1>هذه المساحة محمية</h1><p>يلزم حساب Staff مصرح للوصول إلى تشغيل SaaS. لا يعتمد الحارس على إخفاء الرابط فقط.</p><Link href="/dashboard" className="button button-dark"><ArrowRight size={14} /> العودة للوحة التحكم</Link></main>
  if (staffTwoFactorRequired(user)) return <main className="admin-guard"><ShieldCheck size={28} /><h1>فعّل المصادقة الثنائية أولًا</h1><p>المصادقة الثنائية إلزامية لكل حساب Staff قبل الوصول إلى أقسام الإدارة. أكمل الإعداد من صفحة أمان الحساب ثم عد إلى هنا.</p><Link href="/app/security" className="button button-dark"><ShieldCheck size={14} /> فتح إعدادات الأمان</Link></main>
  if (!config) return <main className="admin-guard"><h1>القسم غير موجود</h1><Link href="/admin" className="button button-dark">لوحة الإدارة</Link></main>
  if (!canAccessStaffSection(user.staffRole, section)) return <main className="admin-guard"><ShieldCheck size={28} /><h1>القسم غير متاح لدورك</h1><p>الدور الحالي: {staffRoleLabels[user.staffRole]}. اطلب من مدير النظام منحك الصلاحية المناسبة.</p><Link href="/admin" className="button button-dark">لوحة الإدارة</Link></main>

  let content: ReactNode
  if (section === 'teachers') {
    const rows = await prisma.workspaceMember.findMany({ where: query ? { OR: [{ user: { name: { contains: query } } }, { user: { email: { contains: query } } }, { workspace: { name: { contains: query } } }] } : undefined, take: 50, orderBy: { createdAt: 'desc' }, select: { id: true, role: true, createdAt: true, user: { select: { id: true, name: true, email: true } }, workspace: { select: { name: true } } } })
    content = rows.length ? rows.map((item) => row(item.id, [<Link key="teacher" href={`/admin/teachers/${item.user.id}`}>{item.user.name}</Link>, item.user.email, item.workspace.name, item.role, formatDate(item.createdAt)])) : emptyState()
  } else if (section === 'plans') {
    const rows = await prisma.plan.findMany({ where: query ? { OR: [{ code: { contains: query } }, { name: { contains: query } }] } : undefined, take: 50, orderBy: { monthlyCents: 'asc' }, select: { id: true, code: true, name: true, monthlyCents: true, yearlyCents: true, trialDays: true, supportTier: true, active: true } })
    content = rows.length ? rows.map((item) => row(item.id, [<Link key="plan" href={`/admin/plans/${item.id}`}>{item.name} ({item.code})</Link>, `${(item.monthlyCents / 100).toFixed(2)} شهريًا`, `${(item.yearlyCents / 100).toFixed(2)} سنويًا`, `${item.active ? 'نشطة' : 'متوقفة'} · تجربة ${item.trialDays} يوم`, item.supportTier])) : emptyState()
  } else if (section === 'subscriptions') {
    const rows = await prisma.subscription.findMany({ where: query ? { OR: [{ workspace: { name: { contains: query } } }, { plan: { name: { contains: query } } }, { plan: { code: { contains: query } } }] } : undefined, take: 50, orderBy: { createdAt: 'desc' }, select: { id: true, status: true, billingCycle: true, currentPeriodEnd: true, cancelAtPeriodEnd: true, workspace: { select: { name: true } }, plan: { select: { code: true, name: true } } } })
    content = rows.length ? rows.map((item) => row(item.id, [<Link key="subscription" href={`/admin/subscriptions/${item.id}`}>{item.workspace.name}</Link>, `${item.plan.name} (${item.plan.code})`, `${item.status} · ${item.billingCycle}`, item.cancelAtPeriodEnd ? 'تلغى بنهاية الفترة' : `ينتهي ${formatDate(item.currentPeriodEnd)}`])) : emptyState()
  } else if (section === 'billing') {
    const rows = await prisma.invoice.findMany({ where: query ? { OR: [{ number: { contains: query } }, { workspace: { name: { contains: query } } }] } : undefined, take: 50, orderBy: { createdAt: 'desc' }, select: { id: true, number: true, status: true, amountCents: true, currency: true, createdAt: true, workspace: { select: { name: true } } } })
    content = rows.length ? rows.map((item) => row(item.id, [<Link key="invoice" href={`/admin/billing/${item.id}`}>{item.number}</Link>, item.workspace.name, `${(item.amountCents / 100).toFixed(2)} ${item.currency}`, item.status, formatDate(item.createdAt)])) : emptyState()
  } else if (section === 'lms-links' || section === 'integrations') {
    const rows = await prisma.lmsLink.findMany({ where: query ? { OR: [{ displayName: { contains: query } }, { publicUrl: { contains: query } }, { workspace: { name: { contains: query } } }] } : undefined, take: 50, orderBy: { createdAt: 'desc' }, select: { id: true, displayName: true, publicUrl: true, status: true, lastCheckedAt: true, createdAt: true, workspace: { select: { name: true } } } })
    content = rows.length ? rows.map((item) => row(item.id, [<span key="name"><Link2 size={14} /> {item.displayName}</span>, <a key="url" href={item.publicUrl} target="_blank" rel="noreferrer">فتح الرابط <ExternalLink size={13} /></a>, item.workspace.name, `${item.status} · ${formatDate(item.lastCheckedAt || item.createdAt)}`])) : emptyState()
  } else if (section === 'usage') {
    const [workspaces, members, invoices, tickets, links, auditEvents] = await Promise.all([prisma.workspace.count(), prisma.workspaceMember.count(), prisma.invoice.count(), prisma.supportTicket.count(), prisma.lmsLink.count(), prisma.auditLog.count()])
    content = <div className="dashboard-metrics usage-metrics"><article className="dash-card"><span>مساحات العمل</span><strong>{workspaces}</strong><small>عدد مساحات SaaS المسجلة</small></article><article className="dash-card"><span>العضويات</span><strong>{members}</strong><small>أعضاء عبر المساحات</small></article><article className="dash-card"><span>الفواتير</span><strong>{invoices}</strong><small>سجلات فوترة</small></article><article className="dash-card"><span>التذاكر</span><strong>{tickets}</strong><small>طلبات دعم</small></article><article className="dash-card"><span>الروابط</span><strong>{links}</strong><small>مراجع LMS فقط</small></article><article className="dash-card"><span>التدقيق</span><strong>{auditEvents}</strong><small>أحداث مسجلة</small></article></div>
  } else if (section === 'reports') {
    const [activeSubscriptions, paidInvoices, openTickets, reachableLinks] = await Promise.all([prisma.subscription.count({ where: { status: { in: ['TRIAL', 'ACTIVE', 'GRACE_PERIOD'] } } }), prisma.invoice.count({ where: { status: 'PAID' } }), prisma.supportTicket.count({ where: { status: { in: ['OPEN', 'IN_PROGRESS', 'WAITING_ON_CUSTOMER'] } } }), prisma.lmsLink.count({ where: { status: 'REACHABLE' } })])
    content = <div className="dashboard-metrics usage-metrics"><article className="dash-card"><span>اشتراكات فعالة</span><strong>{activeSubscriptions}</strong><small>تشمل التجربة والفترات النشطة</small></article><article className="dash-card"><span>فواتير مدفوعة</span><strong>{paidInvoices}</strong><small>بدون كشف بيانات دفع حساسة</small></article><article className="dash-card"><span>تذاكر تحتاج متابعة</span><strong>{openTickets}</strong><small>الحالات المفتوحة حاليًا</small></article><article className="dash-card"><span>روابط قابلة للوصول</span><strong>{reachableLinks}</strong><small>آخر فحص مسجل</small></article></div>
  } else if (section === 'support') {
    const rows = await prisma.supportTicket.findMany({ where: query ? { OR: [{ number: { contains: query } }, { subject: { contains: query } }, { workspace: { name: { contains: query } } }] } : undefined, take: 50, orderBy: { updatedAt: 'desc' }, select: { id: true, number: true, subject: true, status: true, priority: true, updatedAt: true, workspace: { select: { name: true } } } })
    content = rows.length ? rows.map((item) => row(item.id, [<Link key="ticket" href={`/admin/support/${item.id}`}>{item.number}</Link>, item.subject, item.workspace.name, `${item.status} · ${item.priority}`, formatDate(item.updatedAt)])) : emptyState()
  } else if (section === 'staff') {
    const rows = await prisma.user.findMany({ where: { isStaff: true, ...(query ? { OR: [{ name: { contains: query } }, { email: { contains: query } }] } : {}) }, take: 50, orderBy: { createdAt: 'desc' }, select: { id: true, name: true, email: true, isStaff: true, staffRole: true, emailVerifiedAt: true, createdAt: true } })
    content = rows.length ? rows.map((item) => row(item.id, [item.name, item.email, item.staffRole, item.emailVerifiedAt ? 'بريد موثق' : 'بريد غير موثق', formatDate(item.createdAt)])) : emptyState()
  } else if (section === 'audit') {
    const rows = await prisma.auditLog.findMany({ where: query ? { OR: [{ entity: { contains: query } }, { entityId: { contains: query } }, { reason: { contains: query } }] } : undefined, take: 50, orderBy: { createdAt: 'desc' }, select: { id: true, action: true, entity: true, entityId: true, reason: true, createdAt: true, actor: { select: { name: true, email: true } }, workspace: { select: { name: true } } } })
    content = rows.length ? rows.map((item) => row(item.id, [`${item.action} · ${item.entity}`, item.actor?.name || item.actor?.email || 'نظام', item.workspace?.name || 'عام', item.reason || '—', formatDate(item.createdAt)])) : emptyState()
  } else if (section === 'notifications') {
    const rows = await prisma.notification.findMany({ where: query ? { OR: [{ type: { contains: query } }, { title: { contains: query } }, { user: { email: { contains: query } } }] } : undefined, take: 50, orderBy: { createdAt: 'desc' }, select: { id: true, type: true, title: true, readAt: true, createdAt: true, user: { select: { name: true, email: true } }, workspace: { select: { name: true } } } })
    content = rows.length ? rows.map((item) => row(item.id, [item.title, item.user.name || item.user.email, item.workspace?.name || 'عام', item.readAt ? 'مقروء' : 'غير مقروء', formatDate(item.createdAt)])) : emptyState()
  } else if (section === 'coupons') {
    const rows = await prisma.coupon.findMany({ where: query ? { code: { contains: query } } : undefined, take: 50, orderBy: { createdAt: 'desc' }, select: { id: true, code: true, description: true, percentOff: true, active: true, maxRedemptions: true, redeemedCount: true, expiresAt: true } })
    content = rows.length ? rows.map((item) => row(item.id, [item.code, item.description, `${item.percentOff}%`, item.active ? 'نشط' : 'متوقف', `${item.redeemedCount}${item.maxRedemptions === null ? '' : ` / ${item.maxRedemptions}`}`, item.expiresAt ? `ينتهي ${formatDate(item.expiresAt)}` : 'بلا انتهاء'])) : emptyState()
  } else if (section === 'webhooks') {
    const rows = await prisma.billingWebhookEvent.findMany({ where: query ? { OR: [{ provider: { contains: query } }, { eventId: { contains: query } }, { state: { contains: query } }, { errorCode: { contains: query } }] } : undefined, take: 50, orderBy: { receivedAt: 'desc' }, select: { id: true, provider: true, eventId: true, signatureValid: true, state: true, errorCode: true, receivedAt: true, processedAt: true } })
    content = rows.length ? rows.map((item) => row(item.id, [item.provider, item.eventId, item.signatureValid ? 'توقيع صحيح' : 'توقيع مرفوض', item.state, item.errorCode || '—', formatDate(item.processedAt || item.receivedAt)])) : emptyState()
  } else if (section === 'settings') {
    const [workspaces, staff, plans, lastAudit, openTickets, pendingDeletionRequests, failedWebhooks] = await Promise.all([prisma.workspace.count(), prisma.user.count({ where: { isStaff: true } }), prisma.plan.count({ where: { active: true } }), prisma.auditLog.findFirst({ orderBy: { createdAt: 'desc' }, select: { createdAt: true } }), prisma.supportTicket.count({ where: { status: { in: ['OPEN', 'IN_PROGRESS', 'WAITING_ON_CUSTOMER'] } } }), prisma.dataDeletionRequest.count({ where: { status: { in: ['REQUESTED', 'IN_REVIEW', 'APPROVED'] } } }), prisma.billingWebhookEvent.count({ where: { state: { not: 'PROCESSED' } } })])
    content = <div className="admin-settings-stack"><div className="dashboard-metrics usage-metrics"><article className="dash-card"><span>مساحات العمل</span><strong>{workspaces}</strong><small>نطاق SaaS الحالي</small></article><article className="dash-card"><span>Staff</span><strong>{staff}</strong><small>حسابات تشغيل مصرح بها</small></article><article className="dash-card"><span>خطط نشطة</span><strong>{plans}</strong><small>خطط معروضة للبيع</small></article><article className="dash-card"><span>تذاكر مفتوحة</span><strong>{openTickets}</strong><small>تحتاج متابعة تشغيلية</small></article><article className="dash-card"><span>طلبات حذف معلقة</span><strong>{pendingDeletionRequests}</strong><small>تحتاج مراجعة Staff يدوية</small></article><article className="dash-card"><span>Webhooks غير معالجة</span><strong>{failedWebhooks}</strong><small>عتبة تنبيه: أي حدث غير PROCESSED</small></article></div><section className="admin-panel admin-policy-card"><div className="admin-panel-heading"><div><b>سياسة الاحتفاظ ببيانات SaaS</b><span>سياسة تشغيلية واضحة، قابلة للمراجعة، ولا تشمل أي محتوى من قاعدة LMS.</span></div><ShieldCheck size={17} /></div><div className="invoice-table"><div className="invoice-row"><span>الحساب والملف الشخصي</span><span>يستمر أثناء وجود الحساب، ويُعالج طلب التصدير أو الحذف من خلال إجراءات SaaS.</span><span>ملكية المستخدم</span></div><div className="invoice-row"><span>الفوترة والفواتير</span><span>تُحفظ للسجل التجاري والامتثال، مع إخفاء بيانات الدفع الحساسة.</span><span>سجل مالي</span></div><div className="invoice-row"><span>سجلات التدقيق والأمان</span><span>تُحتفظ لفترة تشغيلية مناسبة للتحقيق في الحوادث ومراجعة الوصول.</span><span>وصول Staff فقط</span></div><div className="invoice-row"><span>الدعوات والإشعارات</span><span>الدعوات المنتهية والإشعارات القديمة مرشحة للتنظيف الدوري دون التأثير على الاشتراك.</span><span>تنظيف دوري</span></div></div><p className="dashboard-footer-note"><ShieldCheck size={15} /> آخر حدث تدقيق: {formatDate(lastAudit?.createdAt)}. لا توجد مهمة حذف تلقائي مفعلة في هذه البيئة؛ أي تغيير دائم يحتاج إلى إجراء موثق ومراجعة Staff.</p></section><section className="admin-panel admin-policy-card"><div className="admin-panel-heading"><div><b>حالة الضوابط</b><span>مؤشرات تشغيلية مقروءة من نماذج SaaS الحالية.</span></div><Settings size={17} /></div><div className="admin-links"><span>PostgreSQL الإنتاج: يعتمد على اتصال البيئة</span><span>الدفع: webhook هو مصدر الحقيقة</span><span>النسخ الاحتياطي: مسؤولية بيئة الاستضافة</span><span>التكامل LMS: رابط مرجعي فقط</span><span>المصادقة الثنائية: Staff غير المفعّل محجوب</span><span>طلبات الحذف: مراجعة يدوية، بلا حذف تلقائي</span><span>التنبيه: راقب Webhooks غير PROCESSED وطلبات الحذف المعلقة</span></div></section></div>
  } else {
    const [workspaces, staff, plans, lastAudit] = await Promise.all([prisma.workspace.count(), prisma.user.count({ where: { isStaff: true } }), prisma.plan.count({ where: { active: true } }), prisma.auditLog.findFirst({ orderBy: { createdAt: 'desc' }, select: { createdAt: true } })])
    content = <div className="dashboard-metrics usage-metrics"><article className="dash-card"><span>مساحات العمل</span><strong>{workspaces}</strong><small>نطاق SaaS الحالي</small></article><article className="dash-card"><span>Staff</span><strong>{staff}</strong><small>حسابات تشغيل مصرح بها</small></article><article className="dash-card"><span>خطط نشطة</span><strong>{plans}</strong><small>خطط معروضة للبيع</small></article><article className="dash-card"><span>آخر تدقيق</span><strong>{formatDate(lastAudit?.createdAt)}</strong><small>وقت آخر حدث مسجل</small></article></div>
  }

  const Icon = config.icon
  return <main className="admin-page"><header className="admin-header section-container"><Link href="/admin" className="brand"><span className="brand-mark"><span /><span /><span /></span>مركزية</Link><div><span className="section-eyebrow"><span className="eyebrow-dot" />مساحة الموظفين</span><h1>{config.title} <em>SaaS</em></h1></div><span className="staff-badge"><ShieldCheck size={13} /> Staff</span></header><section className="admin-content section-container"><div className="admin-panel"><div className="admin-panel-heading"><div><b>{config.title}</b><span>{config.description} الحد الأقصى للعرض 50 سجلًا.</span></div><Icon size={17} /></div><div className="admin-links admin-section-nav">{Object.entries(sections).map(([key, value]) => <Link href={`/admin/${key}`} key={key} className={key === section ? 'active' : ''}>{value.title}</Link>)}</div><form method="get" className="admin-search-form" role="search"><label htmlFor="admin-search">بحث في القسم</label><div><input id="admin-search" name="q" defaultValue={query} maxLength={120} placeholder="اسم، بريد، رقم، حالة..." /><button type="submit" className="button button-dark">بحث</button>{query ? <Link href={`/admin/${section}`} className="text-button">مسح</Link> : null}</div></form><div className="invoice-table">{content}</div><p className="dashboard-footer-note"><ShieldCheck size={15} /> هذه شاشة تشغيل SaaS فقط؛ لا تعرض بيانات المتعلمين أو محتوى LMS.</p></div></section></main>
}
